name = CVC Encuentro
description = Layout para encuentroculturaviva.cl, columna principal como header
preview = preview.png
template = cvc_encuentro-layout

; Regions
regions[navigation]     = Navigation Principal
regions[social]         = Social
regions[branding] 	= Header Branding
regions[header]         = Header
regions[nav_cont]       = Navigation Content
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[sidebar]  	= Sidebar
regions[bottom_first] 	= First Buttom
regions[bottom_second] 	= Second Buttom
regions[bottom_third] 	= Third Buttom
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/cvc_encuentro/cvc_encuentro.layout.css
stylesheets[all][] = css/layouts/cvc_encuentro/cvc_encuentro.layout.no-query.css
