name = CVC
description = Layout para cvc-chile.cl, un cuerpo y un sidebar
preview = preview.png
template = cvc-layout

; Regions
regions[navigation]     = Navigation Principal
regions[social]         = Social
regions[header]         = Header
regions[nav_cont]       = Navigation Content
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[sidebar]  = Sidebar
regions[bottom_first] = First Buttom
regions[bottom_second] = Second Buttom
regions[bottom_third] = Third Buttom
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/cvc/cvc.layout.css
stylesheets[all][] = css/layouts/cvc/cvc.layout.no-query.css
